services:
  - type: web
    name: h8-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin
      - key: ADMIN_PASSWORD
        value: user
      - key: DATABASE_URL
        fromDatabase:
          name: h8-database
          property: connectionString

databases:
  - name: h8-database
    databaseName: accounting
    user: accounting
    region: oregon
    plan: free
